id: snapchat_ads_ingestion
description: Snapchat Ads data ingestion pipeline to DuckDB
schedule: daily
start_date: "2024-01-01"

default_connections:
  elastichsearch: my-elasticsearch
  snapchatads: my-snapchatads

