id: linear_ingestion
description: Linear data ingestion pipeline to BigQuery
schedule: daily
start_date: "2025-09-09"

default_connections:
  google_cloud_platform: gcp-default
  linear: linear_connection

