id: cursor_ingestion
description: Cursor data ingestion pipeline to DuckDB
schedule: daily
start_date: "2024-01-01"

default_connections:
  google_cloud_platform: gcp-default
  cursor: cursor_connection

