id: main-test
# schedule: "daily"
schedule: "*/20 * * * *"
# start_date: "2023-06-10"

default_connections:
  gcp: "gcp-default"
  postgres: "neon"
  redshift: "neon-redshift"
  mssql: "mssql-default"
  synapse: "synapse"

